set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports sys_clk_pin]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports sys_rst_n_pin]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports uart_rx_pin]
set_property -dict {PACKAGE_PIN V1 IOSTANDARD LVCMOS33} [get_ports uart_tx_pin]

set_property PACKAGE_PIN D10 [get_ports {led_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[0]}]
set_property PACKAGE_PIN D9 [get_ports {led_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[1]}]
set_property PACKAGE_PIN C9 [get_ports {led_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[2]}]
set_property PACKAGE_PIN B9 [get_ports {led_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[3]}]
set_property PACKAGE_PIN B8 [get_ports {led_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[4]}]
set_property PACKAGE_PIN A8 [get_ports {led_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[5]}]
set_property PACKAGE_PIN C11 [get_ports {led_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[6]}]
set_property PACKAGE_PIN C10 [get_ports {led_pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pin[7]}]

set_property PACKAGE_PIN A9 [get_ports {seg_cs_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs_pin[0]}]
set_property PACKAGE_PIN A10 [get_ports {seg_cs_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs_pin[1]}]
set_property PACKAGE_PIN C14 [get_ports {seg_cs_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs_pin[2]}]
set_property PACKAGE_PIN D14 [get_ports {seg_cs_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs_pin[3]}]

set_property PACKAGE_PIN B11 [get_ports {seg_data_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[0]}]
set_property PACKAGE_PIN A11 [get_ports {seg_data_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[1]}]
set_property PACKAGE_PIN F13 [get_ports {seg_data_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[2]}]
set_property PACKAGE_PIN F14 [get_ports {seg_data_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[3]}]
set_property PACKAGE_PIN D12 [get_ports {seg_data_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[4]}]
set_property PACKAGE_PIN D13 [get_ports {seg_data_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[5]}]
set_property PACKAGE_PIN D15 [get_ports {seg_data_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data_pin[6]}]
#set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports { seg_data_pin[7] }];

